# action.yml
name: 'Codeatlas - Codebase Visualisation'
description: ''
inputs:
  sub_directory:
    description: 'Sub-directory to start visualisation from.'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - name: pull
      shell: bash
      run: docker pull ghcr.io/codeatlashq/codebase-tessellator:0.1.0-rc.3

    - name: 'Codeatlas - Codebase Visualisation'
      shell: bash
      run: docker run --mount type=bind,source="$GITHUB_WORKSPACE",target=$GITHUB_WORKSPACE ghcr.io/codeatlashq/codebase-tessellator:0.1.0-rc.3 tessellate-from-path --repo_path $GITHUB_WORKSPACE/${{ inputs.sub_directory }} --output_path $GITHUB_WORKSPACE/.codeatlas --repo_owner $GITHUB_REPOSITORY_OWNER

    - uses: peter-evans/create-pull-request@v4
      with: 
        add-paths: ".codeatlas/"
        commit-message: "codeatlas: update repo visualization to ${{ github.sha }}."
        committer: "codeatlas-bot <hello@codeatlas.dev>"
        author: "codeatlas-bot <hello@codeatlas.dev>"
        branch: "codeatlas-preview"
        delete-branch: true
        title: "Codeatlas: Update repo visualisation."
        body: |
          Adds files necessary for repo visualization at codeatlas.dev. 
          Preview diagram at: https://codeatlas.dev/github/${{ github.repository }}/codeatlas-preview
          
          (Auto-generated by [codebase-visualizer-action](https://github.com/codeatlasHQ/codebase-visualizer-action))
          
