# action.yml
name: 'Codeatlas - Codebase Visualisation'
description: "The Codeatlas codebase-visualizer action computes what's necessary to visualize codebases through https://codeatlas.dev and automatically adds this data to your repo by raising PRs."inputs:
  sub_directory:
    description: 'Sub-directory to start visualisation from.'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - name: pull
      shell: bash
      run: docker pull ghcr.io/codeatlashq/codebase-tessellator:0.1.2

    - name: 'Codeatlas - Codebase Visualisation'
      shell: bash
      run: docker run --mount type=bind,source="$GITHUB_WORKSPACE",target=$GITHUB_WORKSPACE ghcr.io/codeatlashq/codebase-tessellator:0.1.2 tessellate-from-path --repo_path $GITHUB_WORKSPACE/${{ inputs.sub_directory }} --output_path $GITHUB_WORKSPACE/.codeatlas --repo_owner $GITHUB_REPOSITORY_OWNER

    - uses: peter-evans/create-pull-request@v4
      with: 
        add-paths: ".codeatlas/"
        commit-message: "codeatlas: update repo visualization to ${{ github.sha }}."
        committer: "codeatlas-bot <hello@codeatlas.dev>"
        author: "codeatlas-bot <hello@codeatlas.dev>"
        branch: "codeatlas-preview"
        delete-branch: true
        title: "Codeatlas: Update repo visualisation."
        body: |
          Adds data for codebase visualization at codeatlas.dev. 
          Preview diagram here: https://codeatlas.dev/github/${{ github.repository }}/codeatlas-preview

          After merging, this diagram will become permanently available at https://codeatlas.dev/github/${{ github.repository }}/${{ github.event.repository.default_branch }}
          
          You can use the following badge to embed this link in your README: 
          `![](https://img.shields.io/badge/Codeatlas-Codebase_visualized-323b4f?link=https://codeatlas.dev/github/${{ github.repository }}/${{ github.event.repository.default_branch }}`
          
          ![](https://img.shields.io/badge/Codeatlas-Codebase_visualized-323b4f?link=https://codeatlas.dev/github/${{ github.repository }}/${{ github.event.repository.default_branch }})

          (Auto-generated by [codebase-visualizer-action](https://github.com/codeatlasHQ/codebase-visualizer-action))
          
