# action.yml
name: 'Codeatlas - Codebase Visualisation'
description: ''
inputs:
  sub_directory:
    description: 'Sub-directory to start visualisation from.'
    required: false
    default: ''
  output_path:
    required: false
    default: '.codeatlas'
  output_json_filename:
    required: false
    default: 'codeatlas_cells.json'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3

    # - run: git branch codeatlas
      # shell: bash

    - name: pull
      shell: bash
      run: docker pull ghcr.io/codeatlashq/codebase-tessellator:0.1.0-rc.2
    
    - name: print pwd
      shell: bash
      run: pwd

    - name: ls pwd
      shell: bash
      run: ls

    - name: list workspace
      shell: bash
      run: ls /home/runner/work/flask/flask

    - name: 'Codeatlas - Codebase Visualisation'
      shell: bash
      run: docker run ghcr.io/codeatlashq/codebase-tessellator:0.1.0-rc.2 --mount type=bind,source="$GITHUB_WORKSPACE/${{ inputs.sub_directory }}",target=$GITHUB_WORKSPACE/${{ inputs.sub_directory }} tessellate-from-path --repo_path $GITHUB_WORKSPACE/${{ inputs.sub_directory }} --output_path ${{ inputs.output_path }}

    - run: git add ${{ inputs.output_path }}/${{ inputs.output_json_filename }}
      shell: bash

    - run: git commit -m "Codeatlas visualisation - $GITHUB_SHA"
      shell: bash

    - run: git push
      shell: bash

