# action.yml
name: 'Codeatlas - Codebase Visualisation'
description: ''
inputs:
  sub_directory:
    description: 'Sub-directory to start visualisation from.'
    required: false
    default: ''
  output_path:
    required: false
    default: '.codeatlas'
  output_json_filename:
    required: false
    default: 'codeatlas_cells.json'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3

    - name: pull
      shell: bash
      run: docker pull ghcr.io/codeatlashq/codebase-tessellator:0.1.0-rc.3

    - name: 'Codeatlas - Codebase Visualisation'
      shell: bash
      run: docker run --mount type=bind,source="$GITHUB_WORKSPACE",target=$GITHUB_WORKSPACE ghcr.io/codeatlashq/codebase-tessellator:0.1.0-rc.3 tessellate-from-path --repo_path $GITHUB_WORKSPACE/${{ inputs.sub_directory }} --output_path $GITHUB_WORKSPACE/${{ inputs.output_path }} --repo_owner $GITHUB_REPOSITORY_OWNER

    - uses: peter-evans/create-pull-request@v4
      with: 
        add-paths: "${{ inputs.output_path }}/"
        commit-message: "Codeatlas: Visualize repo at commit ${{ github.sha }}."
        committer: "codeatlas-bot <hello@codeatlas.dev>"
        author: "codeatlas-bot <hello@codeatlas.dev>"
        branch: "codeatlas-bot-branch"
        delete-branch: true
        title: "Codeatlas: Update repo visualisation."
        body: |
          Adds files necessary for repo visualization at codeatlas.dev. 
          Preview diagram at: https://codeatlas.dev/github/${{ github.repository }}/codeatlas-${{ github.sha }}
          
          (Auto-generated by [codebase-visualizer-action](https://github.com/codeatlasHQ/codebase-visualizer-action))
          
